custom:
  message: Config server working

info:
  app:
    name: ${spring.application.name}
  build:
    artifactId:@project.artifactId@
    groupId:@project.groupId@
  java:
    version:@java.version@    
management:
  info:
    env:
      enabled: true
